export type DataOption = {
    label: string;
    value: string;
};

export const campusData: DataOption[] = [
	{ label: 'Campus Externo', value: 'Campus Externo' },
	{ label: 'Casa Central', value: 'Casa Central' },
	{ label: 'Lo Contador', value: 'Lo Contador' },
	{ label: 'Oriente', value: 'Oriente' },
	{ label: 'San Joaquín', value: 'San Joaquín' },
	{ label: 'Villarica', value: 'Villarica' },
];

export const formatData: DataOption[] = [
	{ label: 'Híbrido', value: 'HIB' },
	{ label: 'Online Asincrónico', value: 'OA' },
	{ label: 'Online Combinado', value: 'OC' },
	{ label: 'Remoto', value: 'OL' },
	{ label: 'Online Sincrónico', value: 'OS' },
	{ label: 'Presencial', value: 'PR' },
	{ label: 'Presencial y Online Asincrónico', value: 'PROA' },
	{ label: 'Presencial y Online Combinado', value: 'PROC' },
	{ label: 'Presencial y Online Sincrónico', value: 'PROS' },
	{ label: 'Remoto con Act.Presencial', value: 'REPR' },
];

export const generalFormationData: DataOption[] = [
	{ label: 'Artes', value: 'ARTS' },
	{ label: 'Ciencias Sociales', value: 'CSOC' },
	{ label: 'Ciencia y Tecnología', value: 'CTEC' },
	{ label: 'Ecología Integral y Sustentabilidad', value: 'EISU' },
	{ label: 'Formación Filosófica', value: 'FFIL' },
	{ label: 'Formación Teológica', value: 'FTEO' },
	{ label: 'Humanidades', value: 'HUMS' },
	{ label: 'Pensamiento Matemático', value: 'PMAT' },
	{ label: 'Salud y Bienestar', value: 'SBIE' },
];

export const categoriesData: DataOption[] = [
	{ label: 'Formación Antropológica Ética', value: 'AE' },
	{ label: 'Aprendizaje Servicio', value: 'AS' },
	{ label: 'Formación Teológica', value: 'FT' },
	{ label: 'Cursos orientados a la Investigación', value: 'IN' },
	{ label: 'Metodología Aprendizaje Activo', value: 'MA' },
	{ label: 'Reconocimiento Inclusivo', value: 'RI' },
	{ label: 'Formación Transversal Als Doct', value: 'TD' },
];

export const academicUnitsData: DataOption[] = [
	{ label: 'Acad Inter de Filosofía', value: '68' },
	{ label: 'Actividades Universitarias', value: '0' },
	{ label: 'Agronomía y Sistemas Naturales', value: '11' },
	{ label: 'Antropología', value: '92' },
	{ label: 'Arquitectura', value: '94' },
	{ label: 'Arte', value: '33' },
	{ label: 'Astrofísica', value: '2' },
	{ label: 'Bachillerato', value: '7' },
	{ label: 'Bachillerato Inicia', value: '55' },
	{ label: 'CARA', value: '52' },
	{ label: 'Ciencia Política', value: '45' },
	{ label: 'Ciencias Biológicas', value: '12' },
	{ label: 'College', value: '9' },
	{ label: 'Comunicaciones', value: '28' },
	{ label: 'Construcción Civil', value: '1' },
	{ label: 'Deportes', value: '53' },
	{ label: 'Derecho', value: '17' },
	{ label: 'Desarrollo Sustentable', value: '25' },
	{ label: 'Diseño', value: '59' },
	{ label: 'Economía y Administración', value: '5' },
	{ label: 'Educación', value: '20' },
	{ label: 'Escuela Ciencias de la Salud', value: '16' },
	{ label: 'Escuela de Enfermería', value: '13' },
	{ label: 'Escuela de Gobierno', value: '19' },
	{ label: 'Escuela de Graduados', value: '40' },
	{ label: 'Escuela de Medicina', value: '14' },
	{ label: 'Escuela de Odontología', value: '15' },
	{ label: 'Escuela de Salud Pública', value: '31' },
	{ label: 'Estudios Urbanos', value: '95' },
	{ label: 'Estética', value: '51' },
	{ label: 'Filosofía', value: '67' },
	{ label: 'Física', value: '3' },
	{ label: 'Geografía', value: '57' },
	{ label: 'Historia', value: '56' },
	{ label: 'Ing Matemática y Computacional', value: '23' },
	{ label: 'Ingeniería', value: '4' },
	{ label: 'Ingeniería Biológica y Médica', value: '18' },
	{ label: 'Instituto de Éticas Aplicadas', value: '26' },
	{ label: 'Letras', value: '64' },
	{ label: 'Matemáticas', value: '6' },
	{ label: 'Medicina Veterinaria', value: '24' },
	{ label: 'Movilidad e Intercambio', value: '96' },
	{ label: 'Música', value: '70' },
	{ label: 'Psicología', value: '29' },
	{ label: 'Química', value: '10' },
	{ label: 'Química y Farmacia', value: '8' },
	{ label: 'Requisito Idioma', value: '54' },
	{ label: 'Sociología', value: '91' },
	{ label: 'Teatro', value: '34' },
	{ label: 'Teología', value: '38' },
	{ label: 'Trabajo Social', value: '30' },
	{ label: 'Villarrica', value: '21' },
];

export const programLevelData: DataOption[] = [
	{ label: 'Doctorado', value: 'Doctorado' },
	{ label: 'Magíster', value: 'Magister' },
	{ label: 'Postítulo', value: 'Postitulo' },
	{ label: 'Pregrado', value: 'Pregrado' },
	{ label: 'Provisional', value: 'Provisional' },
];

export const admissionPeriodData: DataOption[] = [
	{ label: '202022', value: '202022' },
  { label: '202120', value: '202120' },
  { label: '202220', value: '202220' },
  { label: '202222', value: '202222' },
  { label: '202320', value: '202320' },
  { label: '202322', value: '202322' },
  { label: '202420', value: '202420' },
  { label: '202422', value: '202422' },
  { label: '202520', value: '202520' },
  { label: '202522', value: '202522' },
  { label: '202620', value: '202620' },
  { label: '202622', value: '202622' },
];

export const schoolData: DataOption[] = [
  { label: 'Actividades Universitarias', value: 'Actividades Universitarias' },
  { label: 'Agronomía y Sistemas Naturales', value: 'Agronomía y Sistemas Naturales' },
  { label: 'Alumnos Condicionales', value: 'Alumnos Condicionales' },
  { label: 'Antropología', value: 'Antropología' },
  { label: 'Arquitectura', value: 'Arquitectura' },
  { label: 'Arte', value: 'Arte' },
  { label: 'Astrofísica', value: 'Astrofísica' },
  { label: 'Bachillerato', value: 'Bachillerato' },
  { label: 'Bachillerato Inicia', value: 'Bachillerato Inicia' },
  { label: 'Ciencia Política', value: 'Ciencia Política' },
  { label: 'Ciencias Biológicas', value: 'Ciencias Biológicas' },
  { label: 'College', value: 'College' },
  { label: 'Comunicaciones', value: 'Comunicaciones' },
  { label: 'Construcción Civil', value: 'Construcción Civil' },
  { label: 'Deportes', value: 'Deportes' },
  { label: 'Derecho', value: 'Derecho' },
  { label: 'Diseño', value: 'Diseño' },
  { label: 'Economía y Administración', value: 'Economía y Administración' },
  { label: 'Educación', value: 'Educación' },
  { label: 'Escuela Ciencias de la Salud', value: 'Escuela Ciencias de la Salud' },
  { label: 'Escuela de Enfermería', value: 'Escuela de Enfermería' },
  { label: 'Escuela de Gobierno', value: 'Escuela de Gobierno' },
  { label: 'Escuela de Graduados', value: 'Escuela de Graduados' },
  { label: 'Escuela de Medicina', value: 'Escuela de Medicina' },
  { label: 'Escuela de Odontología', value: 'Escuela de Odontología' },
  { label: 'Estudios Urbanos', value: 'Estudios Urbanos' },
  { label: 'Estudios de la Familia', value: 'Estudios de la Familia' },
  { label: 'Estética', value: 'Estética' },
  { label: 'Filosofía', value: 'Filosofía' },
  { label: 'Física', value: 'Física' },
  { label: 'Geografía', value: 'Geografía' },
  { label: 'Historia', value: 'Historia' },
  { label: 'Ing Matemática y Computacional', value: 'Ing Matemática y Computacional' },
  { label: 'Ingeniería', value: 'Ingeniería' },
  { label: 'Ingeniería Biológica y Médica', value: 'Ingeniería Biológica y Médica' },
  { label: 'Instituto de Éticas Aplicadas', value: 'Instituto de Éticas Aplicadas' },
  { label: 'Letras', value: 'Letras' },
  { label: 'Matemáticas', value: 'Matemáticas' },
  { label: 'Medicina Veterinaria', value: 'Medicina Veterinaria' },
  { label: 'Movilidad e Intercambio', value: 'Movilidad e Intercambio' },
  { label: 'Música', value: 'Música' },
  { label: 'Psicología', value: 'Psicología' },
  { label: 'Química', value: 'Química' },
  { label: 'Química y Farmacia', value: 'Química y Farmacia' },
  { label: 'Requisito Idioma', value: 'Requisito Idioma' },
  { label: 'Sociología', value: 'Sociología' },
  { label: 'Teatro', value: 'Teatro' },
  { label: 'Teología', value: 'Teología' },
  { label: 'Trabajo Social', value: 'Trabajo Social' },
  { label: 'Villarrica', value: 'Villarrica' },
];