import { vars } from 'nativewind';

export const themes = {
	light: vars({
		'--color-bg': '#FFFFFF',
		'--color-primary-default': '#A9B5DF',
		'--color-primary': '#A9B5DF',
		'--color-secondary-default': '#2D336B',
		'--color-secondary': '#2D336B',
		'--color-schedule-block': '#F1F1F1',
		'--color-days-text': '#1E1E1E',
		'--color-modules-text': '#1E1E1E',
		'--color-text-default': '#1E1E1E',
		'--text-modal-placeholder': '#1E1E1E',
		'--text-modal-focus': '#1E1E1E',
		'--text-modal-button': '#FFFFFF',
		'--border-text-input': '#E1E1E1',
		'--title-search-results': '#1E1E1E',
		'--sigle-search-results': '#2D336B',
		'--name-search-results': '#1E1E1E',
		'--section-search-results': '#4B5563',
		'--teachers-search-results': '#4B5563',
	}),
	dark: vars({
		'--color-bg': '#1E1E1E',
		'--color-primary-default': '#2D336B',
		'--color-primary': '#2D336B',
		'--color-secondary-default': '#A9B5DF',
		'--color-secondary': '#A9B5DF',
		'--color-schedule-block': '#131313',
		'--color-days-text': '#F1F1F1',
		'--color-modules-text': '#F1F1F1',
		'--color-text-default': '#F1F1F1',
		'--text-modal-placeholder': '#FFFFFF',
		'--text-modal-focus': '#FFFFFF',
		'--text-modal-button': '#2D336B',
		'--border-text-input': '#131313',
		'--title-search-results': '#F1F1F1',
		'--sigle-search-results': '#A9B5DF',
		'--name-search-results': '#F1F1F1',
		'--section-search-results': '#9CA3AF',
		'--teachers-search-results': '#9CA3AF',
	}),
};